### PR TITLE
Welcome to Atlantis!

### PR DESCRIPTION
**Pull request by sprice-janrain**
In this pull request we will learn how to use atlantis. There are various commands that are available to you:
* Start by typing `atlantis help` in the comments.
* Next, lets plan by typing `atlantis plan` in the comments. That will run a `terraform plan`.
* Now lets apply that plan. Type `atlantis apply` in the comments. This will run a `terraform apply`.

Thank you for trying out atlantis. For more info on running atlantis in production see https://github.com/hootsuite/atlantis

### CODE REVIEW

**Comment by sprice-janrain** [comment]
atlantis plan prod_va

**Comment by sprice-janrain** [comment]
Ran Plan in 2 directories:
 * `example`
 * `example2`

##example/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan"


```

* To **discard** this plan click [here](https://5207b340.ngrok.io/lock?id=sprice-janrain%252Fatlantis-example%252Fexample%252Fprod_va).
---##example2/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example2
      id: <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan"


```

* To **discard** this plan click [here](https://5207b340.ngrok.io/lock?id=sprice-janrain%252Fatlantis-example%252Fexample2%252Fprod_va).
---

**Comment by sprice-janrain** [comment]
atlantis apply prod_va "/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan"

**Comment by sprice-janrain** [comment]
Ran Apply in 2 directories:
 * `/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan`
 * `/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan`

##/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan/
**Apply Error**
```
exit status 1: running "terraform apply -no-color /tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan \"/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan\"" in "/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example": 
Too many command line arguments. Configuration path expected.

Too many command line arguments. Configuration path expected.

```

---##/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan/
**Apply Error**
```
exit status 1: running "terraform apply -no-color /tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan \"/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan\"" in "/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2": 
Too many command line arguments. Configuration path expected.

Too many command line arguments. Configuration path expected.

```

---

**Comment by sprice-janrain** [comment]
atlantis apply prod_va

**Comment by sprice-janrain** [comment]
Ran Apply in 2 directories:
 * `/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan`
 * `/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan`

##/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example/prod_va.tfplan/
```diff
null_resource.example: Creating...
null_resource.example: Creation complete after 0s (ID: 7970165461313383576)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```
---##/tmp/atlantis/data/repos/sprice-janrain/atlantis-example/1/prod_va/example2/prod_va.tfplan/
```diff
null_resource.example2: Creating...
null_resource.example2: Creation complete after 0s (ID: 7970165461313383576)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```
---

**Comment by sprice-janrain** [comment]
Locks and plans deleted for the projects and environments modified in this pull request:

- path: `sprice-janrain/atlantis-example/example` environment: `prod_va`
- path: `sprice-janrain/atlantis-example/example2` environment: `prod_va`

**Comment by rkonell-janrain** [comment]
atlantis help

**Pull request merged**
